#!/usr/bin/env bash
# Shared helpers for the interactive installer.
# shellcheck disable=SC2034

set -euo pipefail

INSTALL_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DEST="${DEST:-/opt/clp-sync}"
PAIR_PORT="${PAIR_PORT:-18765}"

c_info()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
c_ok()    { printf '\033[1;32mOK\033[0m  %s\n' "$*"; }
c_warn()  { printf '\033[1;33mWARN\033[0m %s\n' "$*"; }
c_err()   { printf '\033[1;31mERR\033[0m  %s\n' "$*" >&2; }

ask() {
  # ask "Prompt" "default" → sets REPLY
  local prompt="$1" default="${2:-}"
  if [[ -n "${default}" ]]; then
    read -r -p "${prompt} [${default}]: " REPLY || true
    REPLY="${REPLY:-${default}}"
  else
    read -r -p "${prompt}: " REPLY || true
  fi
}

ask_yn() {
  # ask_yn "Prompt" "y|n" → returns 0 for yes
  local prompt="$1" default="${2:-y}" yn
  if [[ "${default}" == "y" ]]; then
    read -r -p "${prompt} [Y/n]: " yn || true
    yn="${yn:-y}"
  else
    read -r -p "${prompt} [y/N]: " yn || true
    yn="${yn:-n}"
  fi
  [[ "${yn}" =~ ^[Yy] ]]
}

require_root_install() {
  if [[ "$(id -u)" -ne 0 ]]; then
    c_err "Run as root: sudo ./bin/install.sh"
    exit 1
  fi
}

tailscale_self_name() {
  if command -v tailscale >/dev/null 2>&1; then
    tailscale status --self --json 2>/dev/null | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("Self",{}).get("DNSName","").rstrip(".") or d.get("Self",{}).get("HostName",""))' 2>/dev/null \
      || tailscale status --json 2>/dev/null | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("Self",{}).get("DNSName","").rstrip(".") or "")' 2>/dev/null \
      || true
  fi
}

tailscale_self_ip() {
  if command -v tailscale >/dev/null 2>&1; then
    tailscale ip -4 2>/dev/null | head -1 || true
  fi
}

tailscale_peers() {
  if ! command -v tailscale >/dev/null 2>&1; then
    return 0
  fi
  tailscale status --json 2>/dev/null | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for p in (d.get("Peer") or {}).values():
    if p.get("Online") is False:
        continue
    name = (p.get("DNSName") or "").rstrip(".") or p.get("HostName") or ""
    ips = p.get("TailscaleIPs") or []
    ip = ips[0] if ips else ""
    if name or ip:
        print("%s\t%s" % (name or ip, ip))
' 2>/dev/null || true
}

check_cloudpanel() {
  if command -v clpctl >/dev/null 2>&1 && [[ -f /home/clp/htdocs/app/data/db.sq3 ]]; then
    return 0
  fi
  return 1
}

install_files() {
  c_info "Installing toolkit → ${INSTALL_DEST}"
  mkdir -p "${INSTALL_DEST}"
  rsync -a --delete \
    --exclude '.git/' \
    --exclude 'config.env' \
    "${INSTALL_SRC}/" "${INSTALL_DEST}/"
  chmod 755 "${INSTALL_DEST}/bin/"* 2>/dev/null || true
  mkdir -p /etc/clp-sync /var/lib/clp-sync /var/log/clp-sync /var/tmp/clp-sync
  chmod 700 /etc/clp-sync /var/lib/clp-sync /var/tmp/clp-sync
  c_ok "Files installed"
}

write_config() {
  local role="$1"
  local peer_host="${2:-}"
  local ssh_key="${3:-}"
  local cfg=/etc/clp-sync/config.env

  cat >"${cfg}" <<EOF
# Generated by clp-sync installer — $(date -u +%Y-%m-%dT%H:%M:%SZ)
ROLE=${role}

# Peer over Tailscale (master uses STANDBY_HOST; standby records PRIMARY_HOST)
STANDBY_HOST=${peer_host}
PRIMARY_HOST=${peer_host}
STANDBY_SSH_USER=root
STANDBY_SSH_PORT=22
STANDBY_SSH_KEY=${ssh_key}

CLP_DB_PATH=/home/clp/htdocs/app/data/db.sq3
CLP_SYNC_STATE_DIR=/var/lib/clp-sync
CLP_SYNC_TMP_DIR=/var/tmp/clp-sync
CLP_SYNC_LOG_DIR=/var/log/clp-sync
RSYNC_EXCLUDES_FILE=/opt/clp-sync/excludes/rsync-excludes.txt
BOOTSTRAP_SITE_TYPES=php,nodejs,python,static,reverse-proxy
MYSQL_SKIP_UNCHANGED=1
MYSQL_SKIP_DATABASES=information_schema,performance_schema,sys,mysql
RELOAD_NGINX_ON_STANDBY=1
APPLY_PANEL_DB=1
SYNC_EXTRA_USERS=clp
FAIL_NOTIFY_CMD=
EOF
  chmod 600 "${cfg}"
  echo "${role}" >/etc/clp-sync/role
  chmod 644 /etc/clp-sync/role
  c_ok "Wrote ${cfg} (ROLE=${role})"
}

ensure_packages_master() {
  c_info "Checking packages on master (read tools only)"
  local need=()
  for p in rsync sqlite3 openssl openssh-client; do
    command -v "${p}" >/dev/null 2>&1 || need+=("${p}")
  done
  command -v mysqldump >/dev/null 2>&1 || need+=("mysql-client")
  if ((${#need[@]})); then
    apt-get update -y
    apt-get install -y "${need[@]}" || apt-get install -y rsync sqlite3 openssl openssh-client default-mysql-client || true
  fi
  c_ok "Master tools ready (no CloudPanel changes)"
}

ensure_packages_standby() {
  c_info "Checking packages on standby"
  local need=()
  for p in rsync sqlite3 openssl openssh-server python3; do
    command -v "${p%% *}" >/dev/null 2>&1 || need+=("${p}")
  done
  # openssh-server package name vs sshd binary
  if ! command -v sshd >/dev/null 2>&1 && ! systemctl is-active ssh >/dev/null 2>&1 && ! systemctl is-active sshd >/dev/null 2>&1; then
    need+=("openssh-server")
  fi
  if ((${#need[@]})); then
    apt-get update -y
    apt-get install -y rsync sqlite3 openssl openssh-server python3 || true
  fi
  systemctl enable --now ssh 2>/dev/null || systemctl enable --now sshd 2>/dev/null || true
  c_ok "Standby receiver tools ready"
}

generate_pair_token() {
  openssl rand -hex 16
}
